### PR TITLE
Update Peak Element.c++

### PR DESCRIPTION
**Pull request by Shashank-Tomar-2004**
Wrote the missing statements in the else if() and else() statements.

### CODE REVIEW

**Review by vanshikapandey — CHANGES_REQUESTED** [review]
The code looks incomplete kindly check.

**Comment by Shashank-Tomar-2004** [comment]
I have submitted the same code and it got accepted. You can see it here - 
https://leetcode.com/problems/find-peak-element/submissions/1086739412/

**Comment by Shashank-Tomar-2004** [comment]
Also, please expand the code as it may look some part is missing.

**Review by vanshikapandey — APPROVED** [review]
Kindly make sure to remove redundant code

**Pull request merged**
